spring:
  application:
    name: auth-gateway
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/trello-auth
    username: root
    password: ${MYSQL_PW}
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
server:
  port: 8080
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  healthcheck:
    enabled: true
zuul:
  routes:
    board:
      path: /board/**
      serviceId: board-service