spring:
  application:
    name: socket-service
server:
  port: 8082
eureka:
  client:
    fetchRegistry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka